export const MENTION_CATEGORIES = [
  { id: 'companies', title: 'Companies', icon: 'domain', count: 325 },
  { id: 'accounts', title: 'Accounts', icon: 'analytics', count: 325 },
  { id: 'meetings', title: 'Meetings', icon: 'event', count: 23 },
  { id: 'ad_campaigns', title: 'Ad campaigns', icon: 'campaign', count: 246 },
  { id: 'google_drive', title: 'Google Drive', icon: 'add_to_drive', count: 128 },
  { id: 'industry_vertical', title: 'Industry verticals', icon: 'category', count: 18 },
];

export const MENTION_DATA: Record<string, any[]> = {
  companies: [
    { title: 'Evereve', icon: 'domain' },
    { title: 'Synapse Solutions', icon: 'domain' },
    { title: 'TekTronics Co', icon: 'domain' },
    { title: 'DataRobots', icon: 'domain' },
    { title: 'Vectra AI', icon: 'domain' },
    { title: 'Quantum Shift Analytics', icon: 'domain' },
    { title: 'Cortex Innovations', icon: 'domain' },
    { title: 'Nimbus Logic', icon: 'domain' },
    { title: 'Apex Secure', icon: 'domain' },
    { title: 'Synergia Tech', icon: 'domain' },
  ],
  accounts: [
    { title: '45213578', sub: '45124', badge: 'GA' },
    { title: '98465184', sub: '41245', badge: 'GA' },
    { title: '76767242', sub: '74857', badge: 'DV' },
    { title: '57214442', badge: 'GA' },
    { title: '45213578', sub: '45124', badge: 'GA' },
    { title: '98465184', sub: '41245', badge: 'GA' },
    { title: '76767242', sub: '74857', badge: 'DV' },
    { title: '57214442', badge: 'GA' },
  ],
  ad_campaigns: [
    { title: 'HLM_CDMS_Search_FacialRejuvenation_PV', sub: 'Synapse Solutions • Active' },
    { title: 'HLM_CDMS_Search_FacialRejuvenation_PV', sub: 'Synapse Solutions • Active' },
    { title: 'HLM_CDMS_Search_FacialRejuvenation_PV', sub: 'Synapse Solutions • Active' },
    { title: 'HLM_CDMS_Search_FacialRejuvenation_PV', sub: 'Synapse Solutions • Active' },
    { title: 'HLM_CDMS_Search_FacialRejuvenation_PV', sub: 'Synapse Solutions • Active' },
    { title: 'HLM_CDMS_Search_FacialRejuvenation_PV', sub: 'Synapse Solutions • Active' },
    { title: 'HLM_CDMS_Search_FacialRejuvenation_PV', sub: 'Synapse Solutions • Active' },
  ],
  google_drive: [
    { title: 'Comm Doc: YouTube Shoppable Masthead...', type: 'doc' },
    { title: 'Comm Doc: Performance Max with GMC f...', type: 'sheet' },
    { title: 'Comm Doc: YouTube Sponsorships Take...', type: 'doc' },
    { title: 'Brand Report Comm Doc go/brandreportco...', type: 'sheet' },
    { title: 'Comm Doc: Cost-Per-Hour Masthead [C...', type: 'doc' },
    { title: 'Comm Doc: Smart Bidding Seasonality Adjust...', type: 'doc' },
    { title: 'Case study: Pmax in the hospitality vertical...', type: 'slide' },
    { title: 'Make a Copy [External] PMax Channel Perform...', type: 'doc' },
    { title: 'Account Optimization Score - Report', type: 'sheet' },
    { title: 'Comm Doc: Conversion Lift based on users fo...', type: 'doc' },
  ],
  meetings: [
    { title: 'Operational meeting Synapse Solutions // Google', sub: 'Synapse Solutions • Thu Jan 31, 2026 at 9:30AM PT' },
    { title: 'Synapse Solutions strategic meeting // Google', sub: 'Synapse Solutions • Mon Feb 2, 2026 at 9:30AM PT' },
    { title: 'Quarterly Review ABC Corp // Google Team', sub: 'ABC Corp • Fri Feb 15, 2026 at 11:00AM PT' },
    { title: 'Team Building Workshop // Local Park', sub: 'ABC Corp. • Sat Mar 12, 2026 at 1:00PM PT' },
    { title: 'Client Presentation // Office HQ', sub: 'Acme Corp • Wed Mar 29, 2026 at 2:00PM PT' },
    { title: 'Strategic meeting with C-Level // Google', sub: 'Synapse Solutions • Mon Apr 10, 2026 at 10:00AM PT' },
    { title: 'Monthly Strategy Session // In Person', sub: 'Evereve • Thu Apr 20, 2026 at 3:00PM PT' },
    { title: 'Bi-Weekly with Tekinc // Google', sub: 'Tekinc • Fri May 20, 2026 at 3:00PM PT' },
  ],
  industry_vertical: [
    { title: 'Aerospace' },
    { title: 'Automotive' },
    { title: 'Healthcare' },
    { title: 'Finance' },
    { title: 'Education' },
    { title: 'Technology' },
    { title: 'Aerospace' },
    { title: 'Retail' },
    { title: 'Hospitality' },
    { title: 'Construction' },
  ]
};
