import React from 'react';

export const SourceView = ({ source }: { source: any }) => {
  return (
    <div className="flex flex-col flex-1 bg-white rounded-2xl shadow-[0_1px_2px_rgba(0,0,0,0.05)] border border-[#f1f3f4] relative overflow-hidden h-[calc(100vh-120px)] min-h-[500px]">
      <div className="flex flex-row items-center justify-between p-[16px] bg-[#f8f9fa] border-b border-[#dadce0] shrink-0">
        <div className="flex items-center gap-4">
          <i className="google-symbols text-[#5f6368] text-[24px]">description</i>
          <h1 className="font-['Google_Sans'] font-medium text-[20px] text-[#202124] m-0">{source?.title || 'Document'}</h1>
        </div>
      </div>
      
      <div className="p-[32px] overflow-y-auto flex-1">
        <div className="bg-white rounded-[8px] p-[24px] border border-[#dadce0] shadow-sm max-w-[800px] mx-auto">
          {source?.pageId === 'benchmarks' ? (
            <div className="prose max-w-none text-[#3C4043] font-['Roboto'] font-normal text-[15px] leading-[24px]">
              <h2 className="text-[#202124] font-['Google_Sans'] text-[24px] mb-4">Benchmarks Page for Acme Corp</h2>
              <p>
                Acme Corp generally leads the market in online engagement. Their current conversion rate 
                benchmark sits around 4.2%, outperforming the industry standard of 3.1%. Keep reading for more insights.
              </p>
              <h3 className="text-[#202124] font-['Google_Sans'] text-[18px] mt-6 mb-2">Executive Summary</h3>
              <p className="bg-[#feefc3] p-1 rounded-sm border-l-4 border-[#f9ab00]">
                A silicon valley based technology startup that is advancing artificial intelligence. They are planning to IPO in 2026.
              </p>
              <h3 className="text-[#202124] font-['Google_Sans'] text-[18px] mt-6 mb-2">Google Ads Snapshot</h3>
              <p>
                Overall health is positive, but recent policy updates have affected a few campaigns. The key issues are documented below.
              </p>
              <p className="bg-[#feefc3] p-1 rounded-sm border-l-4 border-[#f9ab00]">
                Disapprovals: 2 Ad Groups in Display campaign ('Spring_Sale_2025') are inactive due to sitelink.
              </p>
              <h3 className="text-[#202124] font-['Google_Sans'] text-[18px] mt-6 mb-2">Primary Opportunity - PMax Optimization</h3>
              <p className="bg-[#feefc3] p-1 rounded-sm border-l-4 border-[#f9ab00]">
                Client reacted positively to a PMax pitch on Jan 15, 2025.
              </p>
              <p className="mt-4 text-[#70757a] text-[13px]">
                Report generated by Connect Sales at 2026-04-20 12:00:00Z. Confidential.
              </p>
            </div>
          ) : (
            <div className="prose max-w-none text-[#3C4043] font-['Roboto'] font-normal text-[15px] leading-[24px]">
              <h2 className="text-[#202124] font-['Google_Sans'] text-[24px] mb-4">{source?.title || 'Document Content'}</h2>
              <p className="bg-[#feefc3] p-1 rounded-sm border-l-4 border-[#f9ab00]">
                This content is highlighted because it was cited in the Connect AI chat.
              </p>
              <p className="mt-4">
                The rest of the document content goes here. It provides more context and details about the cited text.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
